name: Check Main
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  release:
    needs: lint
    uses: ./.github/workflows/release.yml
    secrets: inherit
