name: Check Main
on:
  schedule:
    - cron: "30 8 * * 1"
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  release:
    needs: lint
    uses: ./.github/workflows/release.yml
    secrets: inherit
