# Relucent Governance.
# (c) 2023 Relucent Ltd
# https://relucent.dev

name: Build, Test & Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
      - run: npm run format

  publish:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "21.1"
          registry-url: "https://registry.npmjs.org"

      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - run: |
          npm ci

      - run: |
          npx nx run-many --target=build --all

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ github.base_ref }}" = "dev" ]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-prerelease --preid beta --yes
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-graduate --yes
          else
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --yes
          fi

          npx lerna publish from-git --yes
