name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'

      # lerna version --no-push
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npm ci

          if [ "${{ github.base_ref }}" = "dev" ]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-prerelease --preid beta --sign-git-commit --sign-git-tag --yes
          elif [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-graduate --sign-git-commit --sign-git-tag --yes
          else
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --sign-git-commit --sign-git-tag --yes
          fi

          npx lerna publish from-git --yes
