name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      # lerna version --no-push
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npm install

          if ["${{ github.base_ref }}" = "dev"]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-prerelease --preid beta --yes
          elif ["${{ github.event.pull_request.merged }}" = "true"]; then
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --conventional-graduate --yes
          else
            npx lerna version --conventional-commits --changelog-preset conventionalcommits --yes
          fi

          npx lerna publish from-git --yes
